apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 30
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
        - type: Percent
          value: 10
          periodSeconds: 60
      selectPolicy: Min
      stabilizationWindowSeconds: 30
    scaleUp:
      policies:
        - type: Pods
          value: 5
          periodSeconds: 70
        - type: Percent
          value: 12
          periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 0
